self.Widget_HomeQuestionList1 = QtWidgets.QWidget(self.HomePage_scrollAreaWidgetContents)
self.Widget_HomeQuestionList1.setMinimumSize(QtCore.QSize(0, 120))
self.Widget_HomeQuestionList1.setMaximumSize(QtCore.QSize(16777215, 123))
self.Widget_HomeQuestionList1.setStyleSheet("background-color: rgb(255, 255, 255);")
self.Widget_HomeQuestionList1.setObjectName("Widget_HomeQuestionList1")
self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.Widget_HomeQuestionList1)
self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(10, 10, 1201, 111))
self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
self.horizontalLayout_10.setObjectName("horizontalLayout_10")
spacerItem4 = QtWidgets.QSpacerItem(90, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
self.horizontalLayout_10.addItem(spacerItem4)
self.widget_Vote = QtWidgets.QWidget(self.horizontalLayoutWidget_10)
self.widget_Vote.setMaximumSize(QtCore.QSize(90, 16777215))
self.widget_Vote.setObjectName("widget_Vote")
self.verticalLayoutWidget_14 = QtWidgets.QWidget(self.widget_Vote)
self.verticalLayoutWidget_14.setGeometry(QtCore.QRect(0, 0, 90, 111))
self.verticalLayoutWidget_14.setObjectName("verticalLayoutWidget_14")
self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_14)
self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
self.verticalLayout_19.setObjectName("verticalLayout_19")
spacerItem5 = QtWidgets.QSpacerItem(20, 45, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
self.verticalLayout_19.addItem(spacerItem5)
self.VoteCounter = QtWidgets.QLabel(self.verticalLayoutWidget_14)
self.VoteCounter.setMaximumSize(QtCore.QSize(16777215, 20))
font = QtGui.QFont()
font.setPointSize(10)
font.setBold(False)
font.setWeight(50)
self.VoteCounter.setFont(font)
self.VoteCounter.setAlignment(QtCore.Qt.AlignCenter)
self.VoteCounter.setObjectName("VoteCounter")
self.verticalLayout_19.addWidget(self.VoteCounter)
self.label_Vote = QtWidgets.QLabel(self.verticalLayoutWidget_14)
self.label_Vote.setMaximumSize(QtCore.QSize(100, 20))
font = QtGui.QFont()
font.setPointSize(14)
self.label_Vote.setFont(font)
self.label_Vote.setAlignment(QtCore.Qt.AlignCenter)
self.label_Vote.setObjectName("label_Vote")
self.verticalLayout_19.addWidget(self.label_Vote)
spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
self.verticalLayout_19.addItem(spacerItem6)
self.horizontalLayout_10.addWidget(self.widget_Vote)
self.widget_Answer = QtWidgets.QWidget(self.horizontalLayoutWidget_10)
self.widget_Answer.setMaximumSize(QtCore.QSize(90, 16777215))
self.widget_Answer.setObjectName("widget_Answer")
self.verticalLayoutWidget_16 = QtWidgets.QWidget(self.widget_Answer)
self.verticalLayoutWidget_16.setGeometry(QtCore.QRect(0, 0, 90, 111))
self.verticalLayoutWidget_16.setObjectName("verticalLayoutWidget_16")
self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_16)
self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
self.verticalLayout_21.setObjectName("verticalLayout_21")
spacerItem7 = QtWidgets.QSpacerItem(30, 45, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
self.verticalLayout_21.addItem(spacerItem7)
self.AnswerCounter = QtWidgets.QLabel(self.verticalLayoutWidget_16)
self.AnswerCounter.setMaximumSize(QtCore.QSize(16777215, 20))
font = QtGui.QFont()
font.setPointSize(10)
font.setBold(False)
font.setWeight(50)
self.AnswerCounter.setFont(font)
self.AnswerCounter.setAlignment(QtCore.Qt.AlignCenter)
self.AnswerCounter.setObjectName("AnswerCounter")
self.verticalLayout_21.addWidget(self.AnswerCounter)
self.label_Answer = QtWidgets.QLabel(self.verticalLayoutWidget_16)
self.label_Answer.setMaximumSize(QtCore.QSize(100, 20))
font = QtGui.QFont()
font.setPointSize(14)
self.label_Answer.setFont(font)
self.label_Answer.setAlignment(QtCore.Qt.AlignCenter)
self.label_Answer.setObjectName("label_Answer")
self.verticalLayout_21.addWidget(self.label_Answer)
spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
self.verticalLayout_21.addItem(spacerItem8)
self.horizontalLayout_10.addWidget(self.widget_Answer)
self.QuestionList1Button = QtWidgets.QPushButton(self.horizontalLayoutWidget_10)
self.QuestionList1Button.setMinimumSize(QtCore.QSize(26, 66))
self.QuestionList1Button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
self.QuestionList1Button.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
self.QuestionList1Button.setObjectName("QuestionList1Button")
self.horizontalLayout_10.addWidget(self.QuestionList1Button)
spacerItem9 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
self.horizontalLayout_10.addItem(spacerItem9)
self.verticalLayout_2.addWidget(self.Widget_HomeQuestionList1)
